### ISSUE TITLE
[COMPAT MISMATCH] Not Compatible with ComplexityMeasures.jl?

### ISSUE THREAD

**Issue by TheCedarPrince** [JuliaHealth/NeuroAnalyzer.jl#1]
Hey @AdamWysokinski,

I've been doing some work with @datseris using ComplexityMeasures.jl and was curious if you could help me debug why using NeuroAnalyzer.jl reverts the latest version of ComplexityMeasures.jl (3.6.6) down to version 2.8. I did some investigation myself and concluded that the compat mismatch was because NeuroAnalyzer permits version 0.9 and 0.10 of Wavelets.jl whereas ComplexityMeasures.jl only permits 0.10.

I am not entirely sure how to reconcile the mismatch between the two packages other than forking ComplexityMeasures.jl and adding a lower bound to Wavelets.jl to include version 0.9. Any thoughts Adam and/or George?

Cheers!

~ tcp :deciduous_tree:

**Comment by AdamWysokinski** [comment]
Hi Jacob,
There is a "man in the middle" that causes the problem - WaveletsExt.jl requires Wavelets 0.9.3, thus I had to added 0.9 requirements here. I'll submit a PR to them with the fix. However, it might be necessary to fork the WaveletsExt.jl since my last PR to this repo has not been reviewed for the last two years. Seems like the repo is dead..
ATB, Adam

**Comment by TheCedarPrince** [comment]
Oh -- yea, we may want to fork that, update it with your fixes, and move that into JuliaDSP. It looks unmaintained to me as well @AdamWysokinski.

**Comment by AdamWysokinski** [comment]
I've send a message to its developers, lets wait a few days before moving on.

**Comment by Datseris** [comment]
Im updating ComplexityMeasures.jl right now to also allow wavelets 0.9

**Comment by AdamWysokinski** [comment]
Great news @Datseris, thanks! Nevertheless, I'll try to fix the issue on the WaveletsExt.jl side as well.

**Comment by AdamWysokinski** [comment]
The fork at https://github.com/AdamWysokinski/WaveletsExt.jl should do the trick.

**Comment by Datseris** [comment]
The fork has to replace the dependency in NeuroAnalyzer.jl for it to work at a Pkg.add level. However, in Julia v1.10 or less, that is not possible; you can only have a dependency at a package from the general registry. (I think? If you can someohow replace the dependency of WaveletsExt in NeuroAnalayzer with your fork, then we are golden)

**Comment by AdamWysokinski** [comment]
Here's an idea for temporary solution (I have submitted the PR to the WaveletsExt.jl repo, but with low expectations of their response): what if you remove the installed WaveletsExt package and add the forked version manually (```pkg> add https://github.com/AdamWysokinski/WaveletsExt.jl```)?

**Comment by Datseris** [comment]
yes, this works.

**Comment by AdamWysokinski** [comment]
I'll wait few days and if there is no response, I'll try to register the forked package.

**Comment by Datseris** [comment]
> I'll wait few days and if there is no response, I'll try to register the forked package.

For me a better option is to port your fork to JuliaDSP, or simply fork directly from within JuliaDSP if you are an org member, and then _replace_ the General Registry links to point to the JuliaDSP fork. This is a more community-based approach and is likely to be healthier in the long run.

**Comment by Datseris** [comment]
Finally , ComplexityMeasures v3.7.0 is the one that does the trick.

**Comment by AdamWysokinski** [comment]
Does this mean we can close the issue?

**Comment by Datseris** [comment]
I don't know, someone that uses this WaveletsExt needs to test!

**Comment by AdamWysokinski** [comment]
@TheCedarPrince could you please confirm that using ComplexityMeasures v3.7.0 solves the problem?

**Comment by Datseris** [comment]
It does!

**Comment by AdamWysokinski** [comment]
BTW, the forked version 0.2.2 of WaveletsExt in now in the Julia General registry.
